# Generated by Django 4.1.13 on 2024-07-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_rolle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
