# Generated by Django 4.1.13 on 2024-07-08 06:21

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_options_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolle',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('rolle_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
