# Generated by Django 4.1.13 on 2024-07-08 07:26

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rolle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('create', models.CharField(blank=True, max_length=255, null=True)),
                ('update', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_permission', models.CharField(blank=True, max_length=255, null=True)),
                ('view', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
