# Generated by Django 4.1.13 on 2024-07-08 08:26

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollAsPermission',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.permission')),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rolle')),
            ],
        ),
    ]
