# Generated by Django 4.1.13 on 2024-07-08 09:56

import bson.objectid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rollaspermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAsPermission',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('rolle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rolle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
