# Generated by Django 4.1.13 on 2024-07-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_useraspermission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAsPermission',
            new_name='UserAsRolle',
        ),
    ]
