# Generated by Django 4.1.13 on 2024-07-09 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_useraspermission_userasrolle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userasrolle',
            name='rolle',
        ),
        migrations.RemoveField(
            model_name='userasrolle',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rolle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rolle'),
        ),
        migrations.DeleteModel(
            name='RollAsPermission',
        ),
        migrations.DeleteModel(
            name='UserAsRolle',
        ),
    ]
