# Generated by Django 4.1.13 on 2024-07-09 13:09

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='standards',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='standards',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.standard'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
    ]
