# Generated by Django 4.1.13 on 2024-07-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_teacher_standards_remove_teacher_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
