# Generated by Django 4.1.13 on 2024-07-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_teacher_qualification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
