# Generated by Django 4.1.13 on 2024-07-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
