# Generated by Django 4.1.13 on 2024-07-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
