# Generated by Django 4.1.13 on 2024-07-12 08:56

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.schoolclass'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.schoolclass'),
        ),
    ]
