# Generated by Django 4.1.13 on 2024-07-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_attendanceentery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceEntery',
        ),
    ]
