# Generated by Django 4.1.13 on 2024-07-17 10:30

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('attendance', djongo.models.fields.JSONField()),
            ],
        ),
    ]
