# Generated by Django 4.1.13 on 2024-07-17 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_teacherattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherattendance',
            name='attendance',
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='today_present',
            field=models.BooleanField(null=True),
        ),
    ]
