# Generated by Django 4.1.13 on 2024-07-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_teacherattendance_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
